apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels: { app: myapp }
  template:
    metadata:
      labels: { app: myapp }
    spec:
      containers:
      - name: myapp
        image: ${IMAGE}   # replaced by envsubst
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet: { path: /ready,  port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 3