apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels: { app: myapp }
  template:
    metadata:
      labels: { app: myapp }
    spec:
      imagePullSecrets:          # <-- secret for private Docker Hub
      - name: regcred
      containers:
      - name: myapp
        image: docker.io/yourusername/python-hello:IMAGE_TAG   # replaced by CI
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet: { path: /health, port: 5000 }   # same endpoint = always 200
          initialDelaySeconds: 5
          periodSeconds: 3
